### ISSUE TITLE
(1) Cannot create new project [0]

### ISSUE THREAD

**Issue by asymeon** [AuthEceSoftEng/cenote-api#24] opened 2020-06-05 12:57 UTC
Still getting a 500 error

**Comment by johnantonn** [comment] 2020-06-29 11:12
Should this be closed? @iamnapo @MichaelPap  @asymeon

**Comment by iamnapo** [comment] 2020-06-29 11:21
I'm not sure. I personally tried with multiple accounts and cannot replicate it.

**Comment by johnantonn** [comment] 2020-06-30 12:19
Closing this since the issue did not persist and it could not be reproduced..

**Closed by johnantonn** 2020-06-30 12:19 UTC
Labels: bug
